### ISSUE TITLE
what's this?any piecture to show?

### ISSUE THREAD

**Issue by jackylee1** [alievk/avatarify-desktop#1]
what's this?any piecture to show?is that for android or ios platform?why the app is off in china?

**Comment by alievk** [comment]
This is Avatarify for Desktop based on Qt framework. Take a look https://github.com/alievk/avatarify-desktop/wiki/Avatarify-Desktop

**Comment by jackylee1** [comment]
> This is Avatarify for Desktop based on Qt framework. Take a look https://github.com/alievk/avatarify-desktop/wiki/Avatarify-Desktop

thanks, so kind of you/why your app is removed from app store in china?
