### ISSUE TITLE
App doesn`t work

### ISSUE THREAD

**Issue by BfGanimeshnik** [alievk/avatarify-desktop#26]
When the application starts, it appears in the task manager, but does not start
[VIDEO](https://vimeo.com/617487709)

**Comment by JohanAR** [comment]
What graphics card do you have?

**Comment by BfGanimeshnik** [comment]
GEFORCE RTX 3070

**Comment by BfGanimeshnik** [comment]
![image](https://user-images.githubusercontent.com/55851088/135286778-10bb8a21-5310-44fa-9e38-6d0b79e0ada0.png)

**Comment by JohanAR** [comment]
It's unfortunately a known problem that it doesn't work on RTX 30xx cards, see issue https://github.com/alievk/avatarify-desktop/issues/9

**Comment by BfGanimeshnik** [comment]
ok, thanks
