### ISSUE TITLE
7>D:\avatarify-desktop\avatarify\src\vcam\AkVCamBridge.cpp(22,17): error C2039: "connectService": is not"AkVCam::IpcBridge" member

### ISSUE THREAD

**Issue by zhangpu1987** [alievk/avatarify-desktop#3]
bool AkVCamBridge::allocateDevice() {
    m_ipcBridge.connectService(false);
    m_ipcBridge.setDriverPaths({QDir::currentPath().toStdWString()});
    auto devices = m_ipcBridge.listDevices();
    std::cout << "List of devices:" << std::endl;
    for (const auto &d : devices) {
        std::cout << "\t" << d << std::endl;
    }
    
    bool isStarted{false};
    if (devices.empty()) {
        qDebug() << "No available devices. Need to create one..." << supportedFormats.size();
        m_ipcBridge.deviceCreate(description, supportedFormats);
        devices = m_ipcBridge.listDevices();
        qDebug() << devices.size();
        if (!devices.empty()) {
            m_device = devices[0];
            qDebug() << m_device.c_str();
            for (int i = 1; i < 4; ++i) {
                QThread::sleep(4 * i);
                if ((isStarted = m_ipcBridge.deviceStart(m_device, format))) {
                    break;
                }
            }
            if (!isStarted) {
                return false;
            }
        }
        //m_device = m_ipcBridge.deviceCreate(description, supportedFormats);
        //if (m_device.empty()) { // error during creating the device
        //    std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> converter;
        //    std::cout << "ipcBridge: " << converter.to_bytes(m_ipcBridge.errorMessage()) << std::endl;
        //    return false;
        //}
    } else {
        qDebug() << "There are " << devices.size() << " devices. Choose 0...";
        m_device = devices[0];
        //m_ipcBridge.deviceEdit(m_device, L"Avatarify Camera", supportedFormats);
    }
    if (!isStarted) {
        isStarted = m_ipcBridge.deviceStart(m_device, format);
    }
    if (isStarted) {
        AmplitudeLogger::log("vcam_ok");
        std::cout << "Success initializing " << m_device << std::endl;
        return true;
    } else {
        AmplitudeLogger::log("vcam_fail");
        std::cout << "Error initializing " << m_device << std::endl;
        std::wstring_convert<std::codecvt_utf8<wchar_t>, wchar_t> converter;
        std::cout << "ipcBridge: " << converter.to_bytes(m_ipcBridge.errorMessage()) << std::endl;
        return false;
    }
}

**Comment by zhangpu1987** [comment]
which commit you used in akvirtualcamera??

**Comment by staddy** [comment]
[dd38c54](https://github.com/vlivashkin/akvirtualcamera/commit/dd38c548efa049bb22302492d0f979a7f4f29f7d)
You can see it here:
![image](https://user-images.githubusercontent.com/4605568/112449942-e9947a00-8d64-11eb-9bba-dae6ec771e98.png)

**Comment by staddy** [comment]
https://github.com/vlivashkin/akvirtualcamera/blob/40482cb4842671baaa76a5d4285939bc226ac3eb/VCamUtils/src/ipcbridge.h#L114
The proper way to pull all dependencies:
```
git clone https://github.com/alievk/avatarify-desktop
cd avatarify-desktop
git submodule update --init --recursive
```
