### ISSUE TITLE
Improve output resolution

### ISSUE THREAD

**Issue by epicstar7** [alievk/avatarify-desktop#31]
Hi, amazing app works great, lot of fun to let Einstein talk haha! When is the output resolution going to be improved? Or are there already ways to improve quality or newer technologies to do similar things? Thanks Ali!

**Comment by JohanAR** [comment]
If you train a dataset with higher resolution you would get higher resolution output, assuming your graphics card is powerful enough to run it. See https://github.com/AliaksandrSiarohin/first-order-model for more information on training datasets.

**Comment by Emmanueleze996** [comment]
hi @epicstar7 did you get yours running?
