### ISSUE TITLE
using on google colab

### ISSUE THREAD

**Issue by RawZzzzz** [alievk/avatarify-desktop#38]
how do we run this on google colab sir?

**Comment by JohanAR** [comment]
You don't. This is a Windows program that you run on your computer.

**Comment by RawZzzzz** [comment]
But my PC Don't have GPU it's stills slow on it. That's why I asked. I try using avatarify python on Google colab ,like I use to but it seems to stop working since yesterday. It's showing could not find conda environment avatarify

**Comment by JohanAR** [comment]
No worries. Sorry if my answer was a bit short, but I mean that Avatarify Desktop is just a normal Windows program, like Photoshop or Counter-Strike, so there is no possibility to run it on Colab.

If you need a cloud based version, maybe you could try https://avatarify.ai/
