### ISSUE TITLE
Unable to uninstall the app

### ISSUE THREAD

**Issue by viraj-shah18** [alievk/avatarify-desktop#4]
The app worked great. 

However, I am done using it and now want to uninstall. I tried uninstalling from the control panel, however that did not work. Please guide on how should I uninstall it. Just deleting the folder would do the job?

Thanks

**Comment by alievk** [comment]
Normally you uninstall it from the control panel. What didn't work exactly?

**Comment by viraj-shah18** [comment]
When uninstalling from control panel, the uninstall button on top does nothing i.e. on click it doesn't initiate any kind of pop-up or uninstall program window.

**Comment by staddy** [comment]
@viraj-shah18, you probably have the uninstaller corrupt.
To remove Avatarify from installed programs list, you should open regedit, go to branch:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\
![image](https://user-images.githubusercontent.com/4605568/113613621-27917800-965a-11eb-8855-f4a40256466f.png)
Click on Uninstall entry, search for "Avatarify":
![image](https://user-images.githubusercontent.com/4605568/113613793-5f98bb00-965a-11eb-9b56-3255bff2310e.png)
Then remove the first entry found:
![image](https://user-images.githubusercontent.com/4605568/113614120-bef6cb00-965a-11eb-904c-bccfaacc7ba6.png)
You should also remove Avatarify and .avatarify folders from your home directory.

**Comment by viraj-shah18** [comment]
Thank you for such a nice and elaborate comment. I'll follow these steps.
