### ISSUE TITLE
(base) C:\Users\HP-PC>git clone https://github.com/alievk/avatarify-python.git 'git' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Dera7** [alievk/avatarify-desktop#41]

**Comment by JohanAR** [comment]
It's telling you that you don't have git installed...

Next time just type the question into google and you'll get the answer quicker

**Comment by Dera7** [comment]
Please sir I'm excited to receive a help from you but I'm having an issue
again in my obs studio and I have tried but I'm always getting it wrong the
issues is that after dealing with miniconda no avatar will appear on the
obs and if it's to appear it will be 1 instead of 2 I'm looking forward to
your help  thank you in advance i really appreciate
