### ISSUE TITLE
AM FACING THE SAME ISSUE 

### ISSUE THREAD

**Issue by Donskate** [alievk/avatarify-desktop#45]
AM FACING THE SAME ISSUE, WHEN I FIRST BOUGHT MY LAPTOP IT WAS WORKING PERFECTLY BUT ALL OF A SUDDEN IT STOP WORKING 
![Screenshot](https://user-images.githubusercontent.com/108312559/211195593-cd857a20-fa6a-4990-808e-4e4e4266575e.jpg)

**Comment by JohanAR** [comment]
If you want anyone to be able to help you then you need to learn how to write a proper issue report.
