### ISSUE TITLE
NO OPEN Avatarify with Nvidia 3060 

### ISSUE THREAD

**Issue by aestendrela** [alievk/avatarify-desktop#46]
Good afternoon Yesterday I installed Avatarify and when I turn it on... despite appearing in the task panel as running, the program screen does not appear.
I freaked out growing up that it was some computer problem, I uninstalled everything and did a clean install of windows. Install everything again, and Avatarify... and Not work...
I changed the graphics card for another old 580 and the application works (despite being so slow that nothing can be done...)I would like to know if anyone knows of a solution or if you plan to make an update to be able to use AVATARIFY with the 3060 cards.
 It makes me very angry... It is an application that I really want to try.
Many thanks for everything!!

**Comment by JohanAR** [comment]
#9

**Comment by Emmanueleze996** [comment]
Hi @aestendrela did you successfully complete the step and run_windows.bat
