### ISSUE TITLE
miniconda prompt (stuck at solving environment) 

### ISSUE THREAD

**Issue by samameek** [alievk/avatarify-desktop#47]
stuck at solving environment

**Comment by JohanAR** [comment]
This problem as already been reported, please check open issues before creating a new one.

**Comment by warmfart** [comment]
> This problem as already been reported, please check open issues before creating a new one.

so what is the solution?

**Comment by jackydedon** [comment]
please how do we solve this problem?

**Comment by warmfart** [comment]
@JohanAR hello, you said it has been reported(stuck at solving environments)  But what is the solution?  Kindly drop a link or issue number so I can update myself

**Comment by JohanAR** [comment]
You can't see it because you're all posting in the wrong repository :) Didn't notice that until now, since I get notifications for both.. avatarify-desktop does not use Conda because it's not a python program.

Here is the open issue: https://github.com/alievk/avatarify-python/issues/526
