### ISSUE TITLE
Stuck at solving environments on MSI stealth gaming pc, Nvidia rtx3060  8g ram windows 11. Any useful information will be appreciated

### ISSUE THREAD

**Issue by warmfart** [alievk/avatarify-desktop#49]
Stuck at solving environments on MSI stealth gaming pc, Nvidia rtx3060  8g ram windows 11. Any useful information will be appreciated 

@JohanAR kindly drop the issue number or link to resolve this before subbing this issue as “duplicate”

**Comment by JohanAR** [comment]
Well, now it's a duplicate of #47, which was open at the time you created a new report for the same issue.

Anyway, here's the link to the avatarify-python issue tracker: https://github.com/alievk/avatarify-python/issues/526

**Comment by davi0s** [comment]
> Stuck at solving environments on MSI stealth gaming pc, Nvidia rtx3060 8g ram windows 11. Any useful information will be appreciated
> 
> @JohanAR kindly drop the issue number or link to resolve this before subbing this issue as “duplicate”

write me on here |
san.frdpatrick@gmail.com

**Comment by davi0s** [comment]
whatsapp
+234 811 513 3627
