### ISSUE TITLE
Doesn't install 

### ISSUE THREAD

**Issue by Slaymax0** [alievk/avatarify-desktop#51]
Hi I use Windows 11, with direct x12 , I tried to install avatarify with anaconda3 I reached to a point it stopped the installation, it doesn't install it only say working for like an hours so I had to close I would really like to know if there is any other way I can solve it

**Comment by JohanAR** [comment]
Are you perhaps trying to install avatarify-python? This is the issue tracker for avatarify-desktop.

**Comment by Slaymax0** [comment]
Yeah I'm talking about avatarify python
