### ISSUE TITLE
Using Avatarify Desktop with Google Collab

### ISSUE THREAD

**Issue by debrah01** [alievk/avatarify-desktop#52]
How to make Google Collab wor with the desktop version of Avatarify.

**Comment by JohanAR** [comment]
It does not have remote GPU support

**Comment by debrah01** [comment]
So should I delete avatarify desktop and stick to avatarify python?

**Comment by JohanAR** [comment]
If you need to use Colab, avatarify-python is the only version that currently can integrate with it. Avatarify-desktop requires you to have a graphics card with CUDA support.

If you are a programmer you could of course try to add remote GPU support to avatarify-desktop and submit a pull request or fork the project, but I suspect that would take quite a lot of work.

**Comment by debrah01** [comment]
Trying to run avatarify-python it says no module named cv2 but cv2 has been
renamed to opencv-python. What can be done about this?
