### ISSUE TITLE
AVATARIFY INSTALLATION ISSUES

### ISSUE THREAD

**Issue by RaySuz77** [alievk/avatarify-desktop#55]
I still ding know why my laptop refuse to work properly with the installation of avatarify and I've done everything that's important 😔😔😔 somebody should kindly pls and help me out on how to let it work properly thank you

**Comment by davi0s** [comment]
> I still ding know why my laptop refuse to work properly with the installation of avatarify and I've done everything that's important 😔😔😔 somebody should kindly pls and help me out on how to let it work properly thank you

write me on here |
san.frdpatrick@gmail.com

**Comment by davi0s** [comment]
whatsapps
+234 811 513 3627
