### ISSUE TITLE
File "afy/cam_fomm.py", line 6, in <module> import request ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by mv6677** [alievk/avatarify-desktop#58]
I installed avatarify-python. 
When running run_windows.bat via miniconda an error has appeared :
File "afy/cam_fomm.py", line 6, in <module> import request ModuleNotFoundError: No module named 'requests'
How to fix this error?

**Comment by JohanAR** [comment]
Please check the avatarify-python issue tracker, Avatarify Desktop is a different project. I'm pretty sure this has been reported already so there might be some suggested fixes posted.
