### ISSUE TITLE
Doesnt starts

### ISSUE THREAD

**Issue by 0Slmpnv0** [alievk/avatarify-desktop#64]
I have just downloaded and setted it up. Running programm doesnt open any windows, but use some memory. I can see it in Task Manager
core i7-10700
RTX 4060ti 16gb

**Comment by Updatedme** [comment]
> I have just downloaded and setted it up. Running programm doesnt open any windows, but use some memory. I can see it in Task Manager
> core i7-10700
> RTX 4060ti 

Contact: https://wa.me/message/GXQYWX4XRTXGB1
